<a href="https://colab.research.google.com/github/jbarcenilla21/APRENDIZAJE_AUTOMATICO_23_24/blob/main/0%20INTRODUCCION/0.3.%20Vectores%20y%20matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
lista = []
for i in range(20):
  lista.append(i)
print(lista)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


In [5]:
2 in lista

True

In [6]:
35 in lista

False

In [4]:
lista[0]

0

In [7]:
lista[-1]

19

In [8]:
lista[2:4]

[2, 3]

In [9]:
lista[:5]

[0, 1, 2, 3, 4]

In [10]:
lista[4:]

[4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [11]:
lista[:]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [12]:
import numpy as np

np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(1,10,2)


array([1, 3, 5, 7, 9])

In [14]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [15]:
len(a)

4

In [16]:
min(a)

1

In [17]:
max(a)

4

In [18]:
b = np.array([[1,2,3],[5,6,4],[7,5,2]])
b

array([[1, 2, 3],
       [5, 6, 4],
       [7, 5, 2]])

In [19]:
b[0]

array([1, 2, 3])

In [20]:
b[:,1]

array([2, 6, 5])

In [ ]:
b[2,2]

2

# Revisar la indexación de matrices (filas columnas)

In [21]:
b[0:2, 1:3]

array([[2, 3],
       [6, 4]])

In [29]:
a = np.random.rand(5,5)
a

array([[0.59492037, 0.77799168, 0.38890702, 0.97778473, 0.62574606],
       [0.762927  , 0.92993642, 0.45302377, 0.4744581 , 0.35378187],
       [0.19841587, 0.57462033, 0.50915889, 0.73974965, 0.18520654],
       [0.65682977, 0.13711372, 0.78312701, 0.6785965 , 0.01027015],
       [0.57259676, 0.73576841, 0.32204252, 0.75563313, 0.94908531]])

In [30]:
a.shape

(5, 5)

In [31]:
b  = np.random.rand(5,5)
b

array([[0.04554638, 0.70277622, 0.1044264 , 0.77724607, 0.51416842],
       [0.37699045, 0.08288526, 0.98826932, 0.05591777, 0.18164142],
       [0.46043662, 0.8544222 , 0.2033561 , 0.47602047, 0.91941597],
       [0.39112935, 0.51033197, 0.60401667, 0.74397538, 0.14417142],
       [0.60977195, 0.93994903, 0.56982318, 0.73527655, 0.61545461]])

In [32]:
a + b

array([[0.64046675, 1.4807679 , 0.49333342, 1.7550308 , 1.13991448],
       [1.13991745, 1.01282168, 1.44129309, 0.53037587, 0.53542329],
       [0.65885249, 1.42904253, 0.71251499, 1.21577012, 1.10462251],
       [1.04795912, 0.64744569, 1.38714368, 1.42257188, 0.15444157],
       [1.18236871, 1.67571745, 0.8918657 , 1.49090968, 1.56453992]])

In [33]:
a-b

array([[ 0.54937399,  0.07521546,  0.28448062,  0.20053866,  0.11157764],
       [ 0.38593655,  0.84705116, -0.53524555,  0.41854034,  0.17214044],
       [-0.26202075, -0.27980188,  0.30580279,  0.26372918, -0.73420943],
       [ 0.26570042, -0.37321825,  0.17911035, -0.06537889, -0.13390127],
       [-0.03717518, -0.20418062, -0.24778065,  0.02035658,  0.3336307 ]])

In [34]:
a*b

array([[0.02709647, 0.54675405, 0.04061216, 0.75997934, 0.32173886],
       [0.28761619, 0.07707802, 0.44770949, 0.02653064, 0.06426144],
       [0.09135793, 0.49096837, 0.10354057, 0.35213598, 0.17028185],
       [0.2569054 , 0.06997351, 0.47302177, 0.50485909, 0.00148066],
       [0.34915344, 0.69158481, 0.18350729, 0.55559932, 0.58411893]])

In [35]:
a/b

array([[13.06185874,  1.10702619,  3.7242212 ,  1.2580118 ,  1.21700602],
       [ 2.02373029, 11.21956325,  0.45840112,  8.48492547,  1.94769375],
       [ 0.43092982,  0.67252504,  2.50377979,  1.55402907,  0.20143934],
       [ 1.679316  ,  0.26867554,  1.29653213,  0.91212224,  0.0712357 ],
       [ 0.93903428,  0.7827748 ,  0.56516221,  1.02768561,  1.54208822]])

In [36]:
np.transpose(a)

array([[0.59492037, 0.762927  , 0.19841587, 0.65682977, 0.57259676],
       [0.77799168, 0.92993642, 0.57462033, 0.13711372, 0.73576841],
       [0.38890702, 0.45302377, 0.50915889, 0.78312701, 0.32204252],
       [0.97778473, 0.4744581 , 0.73974965, 0.6785965 , 0.75563313],
       [0.62574606, 0.35378187, 0.18520654, 0.01027015, 0.94908531]])

In [37]:
1/a

array([[ 1.68089722,  1.28536079,  2.57130869,  1.02272   ,  1.59809236],
       [ 1.3107414 ,  1.07534234,  2.20738971,  2.10766765,  2.82660049],
       [ 5.03991948,  1.74027954,  1.96402345,  1.35180868,  5.39937724],
       [ 1.52246449,  7.29321621,  1.27693208,  1.47362977, 97.3695369 ],
       [ 1.74642971,  1.35912331,  3.10517999,  1.32339354,  1.05364606]])

## PROBLEMAS

1. Escribe una función **suma_matrices** que tome dos matrices **NumPy** como argumentos y devuelva una nueva matriz que sea la suma de las dos matrices originales. No utilices la operación de suma incorporada de NumPy (+).

In [40]:
import numpy as np

def suma_matrices(A, B):
  # INTRODUCIR EL CÓDIGO DE LA FUNCIÓN AQUÍ
  # VALIDA QUE LAS MATRICES DE ENTRADA TIENEN LA MISMA DIMENSIÓN
  if not(A.shape == B.shape):
    raise("Dimension erronea")

  suma = np.empty(A.shape)

  for i in range(A.shape[0]):
    for j in range(A.shape[1]):
      suma[i][j] = A[i][j] + B[i][j]
  return suma


# Pruebas
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print(suma_matrices(A, B))

assert np.array_equal(suma_matrices(A, B), np.array([[6, 8], [10, 12]]))


[[ 6.  8.]
 [10. 12.]]


2. Escribe una función **transpuesta** que tome una matriz **NumPy** como argumento y **devuelva su transpuesta**. No utilices la propiedad T de NumPy.

In [45]:
import numpy as np

def transpuesta(A):
  # INTRODUCIR EL CÓDIGO DE LA FUNCIÓN AQUÍ

  lgtbq = np.empty(A.shape[::-1])

  for i in range(A.shape[0]):
    for j in range(A.shape[1]):
      lgtbq[j][i] = A[i][j]
  return lgtbq

# Pruebas
A = np.array([[1, 2, 3],
              [4, 5, 6]])

print(transpuesta(A))
assert np.array_equal(transpuesta(A), np.array([[1, 4], [2, 5], [3, 6]]))

[[1. 4.]
 [2. 5.]
 [3. 6.]]


3. Escribe una función **multiplicar_matrices** que tome dos matrices **NumPy** como argumentos y devuelva una nueva matriz que sea el resultado de la multiplicación de las dos matrices originales. No utilices la operación de multiplicación de matrices incorporada de NumPy (@ o np.dot).

In [ ]:
import numpy as np

def multiplicar_matrices(A, B):
  # INTRODUCIR EL CÓDIGO DE LA FUNCIÓN AQUÍ
  # VALIDA QUE LAS MATRICES DE ENTRADA TIENEN LAS DIMENSIONES
  # ADECUADAS QUE PERMITEN LA MULTIPLICACIÓN MATRICIAL
  if not(A.shape[1] == B.shape[0]):
    raise("Dimension erronea")

  result = np.empty(A.shape[0], B.shape[1])

  for i in range(result.shape[0]):
    for j in range(result.shape[1]):


# Pruebas
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 2]])
assert np.array_equal(multiplicar_matrices(A, B), np.array([[4, 4], [10, 8]]))